global:
  scrape_interval: 5s
  evaluation_interval: 5s  

scrape_configs:
  - job_name: 'springboot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']

  # Optional: scrape more endpoints later
  # - job_name: 'react-server'
  #   static_configs:
  #     - targets: ['host.docker.internal:3000']
