server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /positions/promtail-positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: windows-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: windows
          # This matches all .log files in the folder you mapped in docker-compose
          __path__: /var/log/*.log
